// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RawMaterials.Data;

namespace RawMaterials.Migrations
{
    [DbContext(typeof(RawMaterialsContext))]
    partial class RawMaterialsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RawMaterials.Models.Entities.Advertizment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Media")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("PaymentInfoId")
                        .HasColumnType("bigint");

                    b.Property<int>("TeamWorkId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentInfoId")
                        .IsUnique();

                    b.HasIndex("TeamWorkId");

                    b.ToTable("Advertizments");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Categorys");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Citys");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Countrys");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.EndedDeal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ImporterId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long>("SuplierMaterialId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ImporterId");

                    b.HasIndex("SuplierMaterialId");

                    b.ToTable("EndedDeals");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.FeedBack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("ImporterId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("SuplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImporterId");

                    b.HasIndex("SuplierId");

                    b.ToTable("FeedBacks");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.GlobalPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("GlobalPrices");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.ImporterCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<int>("ImporterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImporterId");

                    b.ToTable("ImporterCategory");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.InterestMaterial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("ImporterId")
                        .HasColumnType("int");

                    b.Property<long>("SuplierMterialId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ImporterId");

                    b.HasIndex("SuplierMterialId");

                    b.ToTable("InterestMaterial");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.Material", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("SubCategoryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Read_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("notification_text")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.NotificationSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("BestDealPeriod")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.PaymentInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Payment_Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Payment_Method")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Payment_Reason")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Paymnet_Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentInfo");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.PriceLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<long>("SuplierMaterialId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SuplierMaterialId");

                    b.ToTable("PriceLog");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Province");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.SubCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategorys");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.SuplierCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<int>("SuplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SuplierId");

                    b.ToTable("SuplierCategory");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.SuplierMaterial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<long>("Quantitiy")
                        .HasColumnType("bigint");

                    b.Property<int>("SuplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("SuplierId");

                    b.ToTable("SuplierMaterial");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Active")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Gender")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nationality")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.Importer", b =>
                {
                    b.HasBaseType("RawMaterials.Models.Entities.User");

                    b.Property<bool>("PremiumAccount")
                        .HasColumnType("tinyint(1)");

                    b.HasDiscriminator().HasValue("Importer");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.Suplier", b =>
                {
                    b.HasBaseType("RawMaterials.Models.Entities.User");

                    b.Property<string>("CommericialRecord")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("PremiumAccount")
                        .HasColumnName("Suplier_PremiumAccount")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("Rank")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Suplier");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.TeamWork", b =>
                {
                    b.HasBaseType("RawMaterials.Models.Entities.User");

                    b.Property<string>("Field_Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasDiscriminator().HasValue("TeamWork");
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.Advertizment", b =>
                {
                    b.HasOne("RawMaterials.Models.Entities.PaymentInfo", "PaymentInfo")
                        .WithOne()
                        .HasForeignKey("RawMaterials.Models.Entities.Advertizment", "PaymentInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RawMaterials.Models.Entities.TeamWork", "TeamWork")
                        .WithMany("Advertizments")
                        .HasForeignKey("TeamWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.City", b =>
                {
                    b.HasOne("RawMaterials.Models.Entities.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.EndedDeal", b =>
                {
                    b.HasOne("RawMaterials.Models.Entities.Importer", "Importer")
                        .WithMany("EndedDeals")
                        .HasForeignKey("ImporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RawMaterials.Models.Entities.SuplierMaterial", "SuplierMaterial")
                        .WithMany("EndedDeals")
                        .HasForeignKey("SuplierMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.FeedBack", b =>
                {
                    b.HasOne("RawMaterials.Models.Entities.Importer", "Importer")
                        .WithMany("FeedBacks")
                        .HasForeignKey("ImporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RawMaterials.Models.Entities.Suplier", "Suplier")
                        .WithMany("FeedBacks")
                        .HasForeignKey("SuplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.GlobalPrice", b =>
                {
                    b.HasOne("RawMaterials.Models.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.ImporterCategory", b =>
                {
                    b.HasOne("RawMaterials.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RawMaterials.Models.Entities.Importer", "Importer")
                        .WithMany("ImporterCategories")
                        .HasForeignKey("ImporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.InterestMaterial", b =>
                {
                    b.HasOne("RawMaterials.Models.Entities.Importer", "Importer")
                        .WithMany("InterestMaterials")
                        .HasForeignKey("ImporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RawMaterials.Models.Entities.SuplierMaterial", "SuplierMterial")
                        .WithMany()
                        .HasForeignKey("SuplierMterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.Material", b =>
                {
                    b.HasOne("RawMaterials.Models.Entities.SubCategory", "SubCategory")
                        .WithMany("Materials")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.Notification", b =>
                {
                    b.HasOne("RawMaterials.Models.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.NotificationSetting", b =>
                {
                    b.HasOne("RawMaterials.Models.Entities.User", "User")
                        .WithOne("NotificationSetting")
                        .HasForeignKey("RawMaterials.Models.Entities.NotificationSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.PaymentInfo", b =>
                {
                    b.HasOne("RawMaterials.Models.Entities.User", "User")
                        .WithMany("PaymentInfos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.PriceLog", b =>
                {
                    b.HasOne("RawMaterials.Models.Entities.SuplierMaterial", "SuplierMaterial")
                        .WithMany()
                        .HasForeignKey("SuplierMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.Province", b =>
                {
                    b.HasOne("RawMaterials.Models.Entities.Country", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.SubCategory", b =>
                {
                    b.HasOne("RawMaterials.Models.Entities.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.SuplierCategory", b =>
                {
                    b.HasOne("RawMaterials.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RawMaterials.Models.Entities.Suplier", "Suplier")
                        .WithMany("SuplierCategories")
                        .HasForeignKey("SuplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RawMaterials.Models.Entities.SuplierMaterial", b =>
                {
                    b.HasOne("RawMaterials.Models.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RawMaterials.Models.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RawMaterials.Models.Entities.Suplier", "Suplier")
                        .WithMany("SuplierMaterials")
                        .HasForeignKey("SuplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
